package gotypes

import (
	"os"
)

func saveToFile(filename string, data string) {
	// Create file
	f, err := os.Create(filename)
	if err != nil {
		panic(err)
	}

	data = putComment("Generated by Gotypes") + putComment("Still in beta, feel free to modify the types to your needs\n") + data

	// Write to file
	_, err = f.WriteString(data)
	if err != nil {
		panic(err)
	}

	// Close file
	f.Close()
}

func combineTypes(types *[]string) string {
	combined := ""
	for _, t := range *types {
		combined += t + "\n\n"
	}

	return combined
}

func putComment(s string) string {
	return "// " + s + "\n"
}
